/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        StandardCalculator calc = new StandardCalculator();
        try {
            calc.divide(5, 5);
        } catch (ArithmeticException e) {
            System.err.println("Something went wrong!!" + e.getMessage());
        }
        
        calc.printResult();

        LogicCalculator calcLogic = new LogicCalculator();

        calcLogic.OR(8, 6);

        calcLogic.printResult();
    }
}
